spring.application.name=springboot-restful-webservices

#server.port=9090

#DMDS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user_management?useSSL=false&serverTimezone=UTC

#spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

#LSFB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# enable all endpoints exposes by actuator by adding below property
management.endpoints.web.exposure.include=*

# to view response of info endpoint
management.info.env.enabled=true

#shows all the details of health endpoint
management.endpoint.health.show-details=always

# property for shutdown
management.endpoint.shutdown.enabled=true


# /INFO endpoint
info.app.name=Spring Boot Restful web Services
info.app.description=Spring Boot Restful Web Services Demo
info.app.version=1.0.0

